datamodule:
  dataset:
    class_path: geoloc.data.datasets.VPAir.VPAirTrainDataset
    init_args:
      root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
      north_align: True
      resize: 504
  dataloader:
    batch_size: 8
    num_workers: 4
    shuffle: True
    drop_last: True
    pin_memory: False

# model:
#   class_path: geoloc.relatedwork.salad.SALADModel
#   init_args:
#     lr: 6.0e-5
#     optimizer: 'adamw'
#     weight_decay: 9.5e-9
#     momentum: 0.9
#     lr_sched: 'linear'
#     lr_sched_args:
#       start_factor: 1
#       end_factor: 0.2
#       total_iters: 4000
#     loss_name: 'MultiSimilarityLoss'
#     miner_name: 'MultiSimilarityMiner'
#     miner_margin: 0.1
#     faiss_gpu: False
model:
  backbone:
    class_path: geoloc.models.backbones.SaladDINOv2Backbone
    _pretrained_ckpt_path: /storage/datasets/AerialLoc/Drone2Sat/ckpts/salad/dino_salad.ckpt
    init_args:
      model_name: dinov2_vitb14
      num_trainable_blocks: 4
      return_token: True
      norm_layer: True
  aggregator:
    class_path: geoloc.models.aggregators.SALAD
    init_args:
      num_channels: 768
      num_clusters: 64
      cluster_dim: 128
      token_dim: 256
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 6.0e-5
      weight_decay: 9.5e-9
  scheduler:
    class_path: torch.optim.lr_scheduler.LinearLR
    init_args:
      start_factor: 1
      end_factor: 0.2
      total_iters: 4000
  loss: 
    class_path: pytorch_metric_learning.losses.MultiSimilarityLoss
    init_args:
      alpha: 1.0
      beta: 50
      base: 0.0
      distance: 
        class_path: pytorch_metric_learning.distances.CosineSimilarity
  miner:
    class_path: pytorch_metric_learning.miners.MultiSimilarityMiner
    init_args:
      epsilon: 0.1
  faiss_gpu: False

trainer:
  accelerator: 'gpu'
  devices: 1
  default_root_dir: './logs/'
  num_nodes: 1
  num_sanity_val_steps: 0
  precision: '16-mixed'
  max_epochs: 10
  check_val_every_n_epoch: 1
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 20