VISUALIZE_TOP_K: True
VISUALIZE_HEATMAP: False
VISUALIZE_MATCHER: True
SAVE_SALAD_MATRIX: False

every_n: 50
benchmark_top_k: [1, 5, 10, 25, 50, 100]
benchmark_recall_at_xmeters: [100, 150, 200, 250, 500, 1000]

# radius_search_meters: 5000.0
# confidence_pass_streak_threshold: 0

dataset:
  class_path: geoloc.data.datasets.ViCoS.AformXQueryImages
  init_args:
    # query_dir: /storage/private/MORS/AFORMX_GOPRO/frames_3fps_1080p/AFormX-flight3-part2
    # metadata_path: /storage/private/MORS/AFORMX_GOPRO/frames_3fps_1080p/AFormX-flight3-part2_3fps_1080p_telemetry.csv
    query_dir: /storage/private/MORS/AFORMX_GOPRO/gopro_3fps/AFormX-flight3-part1/mav0/cam0/data
    metadata_path: /storage/private/MORS/AFORMX_GOPRO/gopro_3fps/AFormX-flight3-part1/frame_telemetry.csv
    skip_first_n_frames: 600
    skip_last_n_frames: 600
    transforms:
      class_path: torchvision.transforms.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.CenterCrop
            init_args:
              size: [1080, 1080]
          - class_path: torchvision.transforms.Resize
            init_args:
              size: [512, 512]

reranking:
  batch_size: 1
  matcher:
    class_path: geoloc.models.matchers.LoMaMatcher
    init_args:
      resolution: 364
      name: loma_R
      num_sample_keypoints: 2048
      filter_threshold: 0.05
      do_compile: False

    # class_path: geoloc.models.reranking.RomaMatchAnythingMatcher
    # init_args:
    #   weights_path: /storage/datasets/AerialLoc/Drone2Sat/ckpts/matchanything_weights/matchanything_roma.ckpt
    #   coarse_res: 448 
    #   upsample_preds: False
    #   symmetric: False
    #   num_sample_keypoints: 5000
    #   do_compile: False

  ransac:
    # class_path: geoloc.opencv.HomographyEstimator
    # init_args:
    #   reproj_threshold: 5.0
    #   maxIters: 5000
    class_path: geoloc.opencv.PnPSolver
    init_args:
      reproj_threshold: 2.0
      maxIters: 2000
