ROTREF_EXP: False

savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/GURSSat/vdbs/test_vdb

anyloc:
  class_path: geoloc.relatedwork.anyloc.AnyLoc
  init_args:
    backbone:
      class_path: geoloc.models.backbones.AnyLocDINOv2Backbone
      init_args:
        facet: value
        layer: 31
    vlad:
      _fit_step: 1
      _use_prefitted: True
      class_path: geoloc.models.aggregators.vlad.VLAD
      init_args:
        num_clusters: 32
        vlad_mode: hard
        desc_dim: 1536
        cache_dir: *savedir
    pca:
      class_path: sklearn.decomposition.PCA
      init_args:
        n_components: 32
        whiten: True

dataset:
  class_path: geoloc.data.datasets.GURS.GURSReferenceDataset
  init_args:
    root: /storage/private/MORS/gurs/
    stride: 500
    tile_size: 500
    border: Ljubljana
    exclude_slo_border_tifs: True

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 32
    distfn: l2
    norm_vec: True