ROTREF_EXP: False

dataset:
  class_path: geoloc.data.datasets.VisLoc.VisLocReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/UAV_VisLoc/
    flight_idx: 5
    tile_size: 1000
    stride: null
    resize: null
    center_crop: null

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 49152
    distfn: l2
    norm_vec: True