ROTREF_EXP: False

dataset:
  # class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: False
    canonical_ori: True

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 49152
    distfn: cosine
    norm_vec: True