savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/anyloc/VPAir/debug

fitstep: 5
vlad_prefitted: /storage/datasets/AerialLoc/Drone2Sat/ckpts/anyloc_aerial_c_centers/c_centers.pt

anyloc:
  class_path: geoloc.relatedwork.anyloc.AnyLoc
  init_args:
    backbone:
      class_path: geoloc.models.backbones.AnyLocDINOv2Backbone
      init_args:
        model_name: "dinov2_vitg14"
        facet: value
        layer: 31
    vlad:
      class_path: geoloc.models.aggregators.vlad.VLAD
      init_args:
        num_clusters: 32
        vlad_mode: hard
        desc_dim: 1536
        cache_dir: *savedir

dataset:
  # class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: False
    canonical_ori: True