ROTREF_EXP: False

savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/segvlad/VPAir/first

model:
  class_path: geoloc.models.relatedwork.segvlad.SegVladModel
  load_checkpoint: /home/grega/geoloc/logs/checkpoints/segvlad/VPAir/segvlad_bb:dinov2_vitg14_agg:vlad_ds:VPAirReferenceImages_ep:1_20260127_131600/last.ckpt

dataset:
  # class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: True

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 1024 # this is with dinov2-giant
    # vdim: 40960 # this is with dinov3-h16plus 
    distfn: l2
    norm_vec: True
    faiss_gpu: True