model:
  class_path: geoloc.models.relatedwork.segvlad.SegVLAD
  init_args:
    desired_height: 600
    desired_width: 800
    vlad_checkpoint: /storage/datasets/AerialLoc/Drone2Sat/ckpts/anyloc_aerial_c_centers/c_centers.pt
    sam_checkpoint: /storage/datasets/AerialLoc/Drone2Sat/ckpts/sam_vit_h_4b8939.pth
    sam_model_type: vit_h
    order: 3
    sam_resize: True
    backbone:
      class_path: geoloc.models.backbones.AnyLocDINOv2Backbone
      init_args:
        model_name: "dinov2_vitg14"
        facet: value
        layer: 31
    aggregator:
      class_path: geoloc.models.aggregators.vlad.VLAD
      init_args:
        num_clusters: 32
        vlad_mode: hard
        desc_dim: 1536
        cache_dir: null
    pca:
      class_path: sklearn.decomposition.PCA
      init_args:
        n_components: 1024
        whiten: True
        svd_solver: arpack
    fit_step: 5

dataset:
  class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  # class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: True

dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer: # Lightning Trainer config
  max_epochs: 1
  accelerator: 'gpu'
  devices: 1
  num_sanity_val_steps: 0

logger: # WandbLogger config
  offline: False
  save_dir: /home/grega/geoloc/logs/

build_config: !include
  file: build_config.yaml
  keys:
    - vdb
    - dataset
benchmark_config: !include benchmark_config.yaml