savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/segvlad/VPAir/debug

fitstep: 5
vlad_prefitted: /storage/datasets/AerialLoc/Drone2Sat/ckpts/anyloc_aerial_c_centers/c_centers.pt

model:
  class_path: geoloc.models.relatedwork.segvlad.SegVLAD
  init_args:
    backbone:
      class_path: geoloc.models.backbones.AnyLocDINOv2Backbone
      init_args:
        model_name: "dinov2_vitg14"
        facet: value
        layer: 31
    aggregator:
      class_path: geoloc.models.aggregators.vlad.VLAD
      init_args:
        num_clusters: 32
        vlad_mode: hard
        desc_dim: 1536
        cache_dir: *savedir
    pca:
      class_path: sklearn.decomposition.PCA
      init_args:
        n_components: 1024
        whiten: True

dataset:
  # class_path: geoloc.data.datasets.VPAir.VPArReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: False
    canonical_ori: False

dataset:
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: False
    canonical_ori: True

dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer: # Lightning Trainer config
  max_epochs: 1
  accelerator: gpu
  devices: 1

logger: # WandbLogger config
  offline: True
  save_dir: /home/grega/geoloc/logs/
