ROTREF_EXP: False

savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/mixvpr/VPAir/paper_no_distractors

mixvpr:
  class_path: geoloc.relatedwork.mixvpr.MixVPRModel
  checkpoint: /home/grega/geoloc/logs/lightning_logs/version_1/checkpoints/epoch=9-step=2360.ckpt

dataset:
  #class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: False
    resize: [512, 512]

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 4096
    distfn: cosine
    norm_vec: True
