ROTREF_EXP: False

savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/mixvpr/VPAir/paper_with_distractors_7030

model:
  class_path: geoloc.relatedwork.mixvpr.MixVPRModel
  checkpoint: /home/grega/geoloc/logs/checkpoints/MixVPR/VPAir/MixVPR_VPAir_MixVPRResNetBackbone_N-align=True_lr=6e-05_bs=8_ep=10_20251107_114746-epoch=09-step=002360.ckpt

dataset:
  #class_path: geoloc.data.datasets.VPAir.VPAirReferenceImages
  class_path: geoloc.data.datasets.VPAir.VPAirTestDatasetReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/Drone2Sat/VPAir
    include_distractors: True
    transforms:
      class_path: torchvision.transforms.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.Resize
            init_args:
              size: [512, 512]

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 4096
    distfn: cosine
    norm_vec: True
