ROTREF_EXP: False

dataset:
  class_path: geoloc.data.datasets.ALTO.ALTOReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/ALTO
    round: 1
    split: Val

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 49152
    distfn: cosine
    norm_vec: True
