ROTREF_EXP: False

savedir: &savedir /storage/datasets/AerialLoc/Drone2Sat/vdbs/salad/VisLoc/paper_7030

salad:
  class_path: geoloc.relatedwork.salad.SALADModel
  checkpoint: /home/grega/geoloc/logs/checkpoints/SALAD/VisLoc/SALAD_VisLoc_SaladDINOv2Backbone_N-align=False_lr=6e-05_bs=8_ep=10_20251107_130623-epoch=09-step=005100.ckpt

dataset:
  class_path: geoloc.data.datasets.VisLoc.VisLocReferenceImages
  init_args:
    root: /storage/datasets/AerialLoc/UAV_VisLoc/
    flight_idx: 1
    tile_size: 1000
    resize: 504

vdb:
  class_path: geoloc.data.vdb.VectorDatabase
  init_args:
    vdim: 8448
    distfn: cosine
    norm_vec: True
